version: '3'
services:
  # Service definition for the first etcd instance.
  etcd1:
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "2379:2379"   # Expose etcd client port
      - "2380:2380"   # Expose etcd peer port
      - "23790:2379"  # Expose etcd client port for grpc-proxy
      - "8080:8080"   # Expose the application port
    networks:
      etcd-network:
        ipv4_address: 192.168.200.2  # Assign a specific IPv4 address
    volumes:
      - /home/bst/voltest/etcd1:/app/data  # Mount a volume for persistent data

  # Service definition for the second etcd instance.
  etcd2:
    build:
      context: .
      dockerfile: proxy-2.dockerfile
    ports:
      - "23791:2379"  # Expose etcd client port
      - "23802:2380"  # Expose etcd peer port
      - "23792:2379"  # Expose etcd client port for grpc-proxy
      - "8081:8080"   # Expose the application port
    networks:
      etcd-network:
        ipv4_address: 192.168.200.3  # Assign a specific IPv4 address
    volumes:
      - /home/bst/voltest/etcd2:/app/data  # Mount a volume for persistent data

  # Service definition for the third etcd instance.
  etcd3:
    build:
      context: .
      dockerfile: proxy-3.dockerfile
    ports:
      - "23793:2379"  # Expose etcd client port
      - "23803:2380"  # Expose etcd peer port
      - "23794:2379"  # Expose etcd client port for grpc-proxy
      - "8082:8080"   # Expose the application port
    networks:
      etcd-network:
        ipv4_address: 192.168.200.4  # Assign a specific IPv4 address
    volumes:
      - /home/bst/voltest/etcd3:/app/data  # Mount a volume for persistent data

# Definition of a custom bridge network for the etcd instances.
networks:
  etcd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24   # Subnet for the network
          gateway: 192.168.200.1     # Gateway IP address
