version: '3'
services:
  etcd1:
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "2379:2379"
      - "2380:2380"
      - "23790:2379"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.2


  etcd2:
    build:
       context: .
       dockerfile: proxy-2.dockerfile
    ports:
      - "23791:2379"
      - "23802:2380"
      - "23792:2379"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.3

  etcd3:
    build:
       context: .
       dockerfile: proxy-3.dockerfile
    ports:
      - "23793:2379"
      - "23803:2380"
      - "23794:2379"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.4



  gin-app:
    build:
          context: .
          dockerfile: app.dockerfile
    ports:
      - "8080:8080"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.5
    depends_on:
      - etcd1
      - etcd2
      - etcd3

networks:
  etcd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1      