version: '3'
services:
  etcd1:
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - "2379:2379"
      - "2380:2380"
      - "23790:2379"
      - "8080:8080"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.2
    volumes:
      - /home/bst/voltest/etcd1:/app/data

  etcd2:
    build:
       context: .
       dockerfile: proxy-2.dockerfile
    ports:
      - "23791:2379"
      - "23802:2380"
      - "23792:2379"
      - "8081:8080"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.3
    volumes:
      - /home/bst/voltest/etcd2:/app/data

  etcd3:
    build:
       context: .
       dockerfile: proxy-3.dockerfile
    ports:
      - "23793:2379"
      - "23803:2380"
      - "23794:2379"
      - "8082:8080"
    networks:
      etcd-network:
        ipv4_address: 192.168.200.4
    volumes:
      - /home/bst/voltest/etcd3:/app/data

networks:
  etcd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1
  
